version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: movo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: movo_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: movo2025
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movo_system"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:


