
services:
  db:
    image: postgis/postgis:15-3.4-alpine
    restart: always
    environment:
      POSTGRES_DB: movo_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: movo2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgbouncer:
    image: edoburu/pgbouncer:1.18.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      AUTH_TYPE: md5
      AUTH_FILE: /etc/pgbouncer/userlist.txt
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer_userlist.txt:/etc/pgbouncer/userlist.txt:ro
    ports:
      - "6432:6432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -h db -U postgres -p 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: always
    deploy:
      replicas: 4
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:movo2025@pgbouncer:6432/movo_system"
      APP_MODULE: "backend.app:socket_app"
      WORKERS: "6"
      REDIS_URL: "redis://redis:6379/0"
      SOCKET_IO_PATH: "socket.io"
      PYTHONIOENCODING: "utf-8"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      # Performance optimizations
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      WORKER_CLASS: "uvicorn.workers.UvicornWorker"
      WORKER_CONNECTIONS: "1000"
      MAX_REQUESTS: "1000"
      MAX_REQUESTS_JITTER: "100"
      PRELOAD_APP: "true"
    expose:
      - "8000"
    depends_on:
      pgbouncer:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8000/health || curl -fsS http://localhost:8000/api/v1/orders/counts || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'
    depends_on:
      app:
        condition: service_started
    ports:
      - "8000:80"
    environment:
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movo-ts/dist:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=movo2025
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - pgbouncer
      - redis

volumes:
  grafana_data:

